FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY proyecto ./proyecto
COPY keycloak_config.py ./

EXPOSE 8002

CMD ["uvicorn", "proyecto.src.main:app", "--host", "0.0.0.0", "--port", "8002"]
